//! `rust/build.rs` — compile-time enumerator of `shards/**/*.mirror`.
//!
//! Emitted by Reed 2026-07-23 as Tick 1 of the `rust/src/spectral.rs`
//! landing per Taut substrate-scout verdict-b (macro-territory partial).
//! Alex 2026-07-22 verbatim: "each shard IS a Connes spectral triple.
//! Prismqueer formalizes into the triple. What if we had
//! rust/src/spectral.rs" → Alex 2026-07-23: "Before we do that ground
//! with Taut in prismqueer. This might be macro territory."
//!
//! ## What Taut found
//!
//! - `prism/prismqueer/src/bundle.rs:71-193` already encodes the Connes
//!   (A, H, D) triple as a trait tower (`Fiber` = H, `Connection` = A,
//!   `Transport` = D via bounded commutator, `Bundle` = composite).
//! - `prism/prismqueer/src/lib.rs:216-238` already exports `apply_h` as
//!   the operator-on-Hilbert-space action.
//! - `prism/projections/src/lib.rs:96` already exports the
//!   `#[proc_macro] declaration` shard-decl → Rust-item emitter.
//! - Gap: no build.rs at rust/ or prismqueer/ altitude reads
//!   `shards/**/*.mirror` at compile time. The only `.mirror`
//!   `include_str!` in the tree is `bootstrap/src/song.rs:32` — DEAD
//!   altitude per memory `feedback-bootstrap-is-dead`.
//!
//! ## Tick 1 scope
//!
//! Walks `../shards/**/*.mirror` from the crate root at cargo build
//! time, emits `$OUT_DIR/shard_manifest.rs` containing a single
//! `pub const SHARD_PATHS: &[&str]` sorted lexicographically. Zero
//! parsing, zero binding — smallest possible pipeline proof.
//!
//! ## Ticks 2+ forward-promises (NOT this landing)
//!
//! - Tick 2: parse each shard's `type` / `action` / `bilateral` blocks;
//!   emit `pub const SHARDS: &[ShardMeta]` with structured metadata.
//! - Tick 3: emit `impl prismqueer::bundle::Bundle for @<species>`
//!   per shard — binds each shard to the (A, H, D) trait tower.
//! - Ticks 4-N: retire hardcoded-arm classes 1+2 (`VERBS` const +
//!   verb dispatch in `main.rs`), 3 (`at_operator` `@io/*` arms in
//!   `main.rs`), 5 (`dispatch_spec_property` strip_prefix arms in
//!   `liquid.rs`), and 6 (`pillar::dispatch` predicate arms in
//!   `liquid.rs`).
//!
//! ## Marker
//!
//! `[substrate-floor:@io-boundary]` — build.rs is `@io/fs.read_dir` +
//! `@io/fs.write_file` at cargo compile-time altitude. Justified per
//! feedback-no-rust-extension-shortcut: compile-time shard-decl
//! binding cannot be achieved by shard-body + runtime `@io` composition
//! (that would relocate hardcoded arms to runtime string-dispatch
//! rather than structurally retire them).

use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let out_path = Path::new(&out_dir).join("shard_manifest.rs");

    let shards_root = PathBuf::from("../shards");

    println!("cargo:rerun-if-changed=../shards");

    let mut paths: Vec<String> = Vec::new();
    if shards_root.is_dir() {
        walk_mirror_files(&shards_root, &shards_root, &mut paths);
    }
    paths.sort();

    let mut generated = String::new();
    generated.push_str("// Generated by rust/build.rs — DO NOT EDIT.\n");
    generated.push_str(
        "// One entry per shards/**/*.mirror at cargo build time.\n\n",
    );
    generated.push_str("pub const SHARD_PATHS: &[&str] = &[\n");
    for p in &paths {
        generated.push_str(&format!("    {:?},\n", p));
    }
    generated.push_str("];\n");

    let mut f = fs::File::create(&out_path)
        .expect("create shard_manifest.rs in OUT_DIR");
    f.write_all(generated.as_bytes())
        .expect("write shard_manifest.rs");
}

fn walk_mirror_files(root: &Path, dir: &Path, out: &mut Vec<String>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk_mirror_files(root, &path, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("mirror") {
            let rel = path.strip_prefix(root).unwrap_or(&path);
            out.push(format!("shards/{}", rel.display()));
        }
    }
}
