//! emit_rust — Rust code emitter for compiled .mirror declarations.
//!
//! Crystal → .rs files. Takes a `MirrorFragment` (or `CompiledShatter`)
//! and produces Rust source code.
//!
//! ## Mapping
//!
//! - `type color = red | blue`  →  `pub enum Color { Red, Blue }`
//! - `type user { name: text }` →  `pub struct User { pub name: String }`
//! - `type point`               →  `pub struct Point;`
//! - `grammar @test { ... }`    →  `pub mod test { ... }`
//! - `action boot(identity)`    →  `pub fn boot(identity: Identity) { todo!() }`
//! - `property p(g) <= verdict` →  `pub fn p(g: &Grammar) -> Verdict { todo!() }`

use crate::declaration::{DeclKind, MirrorData, MirrorFragment, MirrorFragmentExt, OpticOp};
use crate::mirror_runtime::CompiledShatter;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Emit Rust source code from a compiled shatter artifact.
pub fn emit_rust(compiled: &CompiledShatter) -> String {
    emit_rust_fragment(&compiled.fragment)
}

/// Emit Rust source code from a MirrorFragment.
pub fn emit_rust_fragment(frag: &MirrorFragment) -> String {
    let mut output = String::new();
    output.push_str("// Generated by mirror craft --target rust\n");
    output.push_str("// Do not edit \u{2014} this file is derived from .mirror source\n\n");

    emit_frag(frag, &mut output, 0);
    output
}

// ---------------------------------------------------------------------------
// Fragment dispatch
// ---------------------------------------------------------------------------

fn emit_frag(frag: &MirrorFragment, out: &mut String, indent: usize) {
    let data = MirrorData::decode_from_fragment(frag.mirror_data());
    match data.kind {
        DeclKind::Type => emit_type(&data, frag, out, indent),
        DeclKind::Grammar => emit_module(&data, frag, out, indent),
        DeclKind::Action => emit_function(&data, out, indent),
        DeclKind::Property => emit_property(&data, out, indent),
        DeclKind::In => { /* use statement — skip for now */ }
        DeclKind::Out => { /* pub export — skip for now */ }
        DeclKind::Form => emit_form_container(&data, frag, out, indent),
        _ => {
            write_indent(out, indent);
            out.push_str(&format!("// {}: {}\n", data.kind.as_str(), data.name));
        }
    }
}

// ---------------------------------------------------------------------------
// Type emission
// ---------------------------------------------------------------------------

fn emit_type(data: &MirrorData, frag: &MirrorFragment, out: &mut String, indent: usize) {
    let name = to_pascal_case(&data.name);

    if !data.variants.is_empty() {
        emit_enum(data, &name, out, indent);
    } else if has_typed_fields(data, frag) {
        emit_struct_with_fields(data, frag, &name, out, indent);
    } else if !data.params.is_empty() {
        emit_generic_struct(data, &name, out, indent);
    } else if !frag.mirror_children().is_empty() {
        emit_struct_with_children(frag, &name, out, indent);
    } else {
        write_indent(out, indent);
        out.push_str(&format!("pub struct {};\n", name));
    }
}

fn emit_enum(data: &MirrorData, name: &str, out: &mut String, indent: usize) {
    write_indent(out, indent);
    out.push_str(&format!("pub enum {} {{\n", name));
    for variant in &data.variants {
        write_indent(out, indent + 1);
        out.push_str(&format!("{},\n", to_pascal_case(variant)));
    }
    write_indent(out, indent);
    out.push_str("}\n");
}

fn emit_struct_with_fields(
    data: &MirrorData,
    frag: &MirrorFragment,
    name: &str,
    out: &mut String,
    indent: usize,
) {
    let subset_ref = extract_subset_ref(data);

    write_indent(out, indent);
    out.push_str(&format!("pub struct {} {{\n", name));

    for param in &data.params {
        if let Some((field_name, field_type)) = parse_field(param) {
            write_indent(out, indent + 1);
            out.push_str(&format!(
                "pub {}: {},\n",
                to_snake_case(&field_name),
                map_type(&field_type)
            ));
        }
    }

    for child in frag.mirror_children() {
        let cd = MirrorData::decode_from_fragment(child.mirror_data());
        if cd.kind == DeclKind::Type || cd.kind == DeclKind::Binding {
            let field_type = if !cd.params.is_empty() {
                cd.params[0].clone()
            } else if !cd.variants.is_empty() {
                cd.variants[0].clone()
            } else {
                continue;
            };
            write_indent(out, indent + 1);
            out.push_str(&format!(
                "pub {}: {},\n",
                to_snake_case(&cd.name),
                map_type(&field_type)
            ));
        }
    }

    write_indent(out, indent);
    out.push_str("}\n");

    if let Some(parent_type) = subset_ref {
        out.push('\n');
        write_indent(out, indent);
        let parent_name = to_pascal_case(&parent_type);
        out.push_str(&format!("impl From<{}> for {} {{\n", parent_name, name));
        write_indent(out, indent + 1);
        out.push_str(&format!("fn from(_value: {}) -> Self {{\n", parent_name));
        write_indent(out, indent + 2);
        out.push_str("todo!()\n");
        write_indent(out, indent + 1);
        out.push_str("}\n");
        write_indent(out, indent);
        out.push_str("}\n");
    }
}

fn emit_generic_struct(data: &MirrorData, name: &str, out: &mut String, indent: usize) {
    write_indent(out, indent);
    let generics: Vec<String> = data.params.iter().map(|p| to_pascal_case(p)).collect();
    out.push_str(&format!("pub struct {}<{}>;\n", name, generics.join(", ")));
}

fn emit_struct_with_children(frag: &MirrorFragment, name: &str, out: &mut String, indent: usize) {
    write_indent(out, indent);
    out.push_str(&format!("pub struct {};\n", name));

    for child in frag.mirror_children() {
        emit_frag(child, out, indent);
    }
}

// ---------------------------------------------------------------------------
// Grammar → module
// ---------------------------------------------------------------------------

fn emit_module(data: &MirrorData, frag: &MirrorFragment, out: &mut String, indent: usize) {
    let mod_name = strip_grammar_prefix(&data.name);
    write_indent(out, indent);
    out.push_str(&format!("pub mod {} {{\n", to_snake_case(&mod_name)));

    for child in frag.mirror_children() {
        emit_frag(child, out, indent + 1);
    }

    write_indent(out, indent);
    out.push_str("}\n");
}

// ---------------------------------------------------------------------------
// Action → function
// ---------------------------------------------------------------------------

fn emit_function(data: &MirrorData, out: &mut String, indent: usize) {
    write_indent(out, indent);
    let fn_name = to_snake_case(&data.name);

    let params_str = if data.params.is_empty() {
        String::new()
    } else {
        data.params
            .iter()
            .map(|p| {
                if let Some((name, typ)) = parse_field(p) {
                    format!("{}: {}", to_snake_case(&name), map_type(&typ))
                } else {
                    format!("{}: {}", to_snake_case(p), to_pascal_case(p))
                }
            })
            .collect::<Vec<_>>()
            .join(", ")
    };

    let return_type = if let Some(ref rt) = data.return_type {
        format!(" -> {}", map_type(rt))
    } else if data.optic_ops.contains(&OpticOp::Fold) {
        " -> Imperfect<Crystal, Error, Loss>".to_string()
    } else {
        String::new()
    };

    out.push_str(&format!(
        "pub fn {}({}){} {{\n",
        fn_name, params_str, return_type
    ));
    write_indent(out, indent + 1);
    out.push_str("todo!()\n");
    write_indent(out, indent);
    out.push_str("}\n");
}

// ---------------------------------------------------------------------------
// Property → function
// ---------------------------------------------------------------------------

fn emit_property(data: &MirrorData, out: &mut String, indent: usize) {
    write_indent(out, indent);
    let fn_name = to_snake_case(&data.name);

    let params_str = if data.params.is_empty() {
        String::new()
    } else {
        data.params
            .iter()
            .map(|p| {
                if let Some((name, typ)) = parse_field(p) {
                    format!("{}: &{}", to_snake_case(&name), to_pascal_case(&typ))
                } else {
                    format!("{}: &{}", to_snake_case(p), to_pascal_case(p))
                }
            })
            .collect::<Vec<_>>()
            .join(", ")
    };

    out.push_str(&format!(
        "pub fn {}({}) -> Imperfect<(), PropertyError, PropertyLoss> {{\n",
        fn_name, params_str
    ));
    write_indent(out, indent + 1);
    out.push_str("todo!()\n");
    write_indent(out, indent);
    out.push_str("}\n");
}

// ---------------------------------------------------------------------------
// Form container (top-level form @name { ... })
// ---------------------------------------------------------------------------

fn emit_form_container(
    data: &MirrorData,
    frag: &MirrorFragment,
    out: &mut String,
    indent: usize,
) {
    if data.name.starts_with('@') || !frag.mirror_children().is_empty() {
        let mod_name = strip_grammar_prefix(&data.name);
        if !mod_name.is_empty() {
            write_indent(out, indent);
            out.push_str(&format!("pub mod {} {{\n", to_snake_case(&mod_name)));
            for child in frag.mirror_children() {
                emit_frag(child, out, indent + 1);
            }
            write_indent(out, indent);
            out.push_str("}\n");
        } else {
            for child in frag.mirror_children() {
                emit_frag(child, out, indent);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn write_indent(out: &mut String, indent: usize) {
    for _ in 0..indent {
        out.push_str("    ");
    }
}

fn has_typed_fields(data: &MirrorData, frag: &MirrorFragment) -> bool {
    data.params.iter().any(|p| p.contains(':'))
        || frag.mirror_children().iter().any(|c| {
            let cd = c.mirror_data();
            (cd.kind == DeclKind::Type || cd.kind == DeclKind::Binding)
                && (!cd.params.is_empty() || !cd.variants.is_empty())
        })
}

fn parse_field(s: &str) -> Option<(String, String)> {
    let parts: Vec<&str> = s.splitn(2, ':').collect();
    if parts.len() == 2 {
        Some((parts[0].trim().to_string(), parts[1].trim().to_string()))
    } else {
        None
    }
}

fn extract_subset_ref(data: &MirrorData) -> Option<String> {
    if data.optic_ops.contains(&OpticOp::Subset) {
        data.params
            .iter()
            .find(|p| p.starts_with('<'))
            .map(|p| p.trim_start_matches('<').trim().to_string())
    } else {
        None
    }
}

fn strip_grammar_prefix(name: &str) -> String {
    let stripped = name.trim_start_matches('@');
    stripped.replace('/', "_")
}

fn map_type(mirror_type: &str) -> String {
    let t = mirror_type.trim();

    if let Some(idx) = t.find('(') {
        let base = &t[..idx];
        let inner = &t[idx + 1..t.len() - 1];
        let params: Vec<&str> = inner.split(',').map(|s| s.trim()).collect();
        let mapped_params: Vec<String> = params.iter().map(|p| map_type(p)).collect();

        return match base {
            "option" => format!("Option<{}>", mapped_params.join(", ")),
            "result" => format!("Result<{}>", mapped_params.join(", ")),
            "vec" => format!("Vec<{}>", mapped_params.join(", ")),
            "hashmap" => format!("HashMap<{}>", mapped_params.join(", ")),
            "imperfect" => format!("Imperfect<{}>", mapped_params.join(", ")),
            _ => format!("{}<{}>", to_pascal_case(base), mapped_params.join(", ")),
        };
    }

    if t.starts_with('[') && t.ends_with(']') {
        let inner = &t[1..t.len() - 1];
        return format!("Vec<{}>", map_type(inner));
    }

    match t {
        "text" | "string" => "String".to_string(),
        "nat" => "u64".to_string(),
        "f64" => "f64".to_string(),
        "f32" => "f32".to_string(),
        "u8" => "u8".to_string(),
        "u16" => "u16".to_string(),
        "u32" => "u32".to_string(),
        "u64" => "u64".to_string(),
        "usize" => "usize".to_string(),
        "i8" => "i8".to_string(),
        "i16" => "i16".to_string(),
        "i32" => "i32".to_string(),
        "i64" => "i64".to_string(),
        "bool" => "bool".to_string(),
        "str" => "&str".to_string(),
        "ref" => "String".to_string(),
        "oid" => "Oid".to_string(),
        "loss" => "Loss".to_string(),
        "prism" => "Prism".to_string(),
        "verdict" => "Verdict".to_string(),
        "imperfect" => "Imperfect<Crystal, Error, Loss>".to_string(),
        _ => to_pascal_case(t),
    }
}

fn to_pascal_case(s: &str) -> String {
    s.split(['_', '-', '/'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => {
                    let mut s = first.to_uppercase().to_string();
                    s.extend(chars);
                    s
                }
            }
        })
        .collect()
}

fn to_snake_case(s: &str) -> String {
    let s = s.replace(['-', '/'], "_");
    if s.chars()
        .all(|c| c.is_lowercase() || c == '_' || c.is_numeric())
    {
        return s;
    }

    let mut result = String::new();
    let mut prev_was_upper = false;
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 && !prev_was_upper {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
            prev_was_upper = true;
        } else {
            prev_was_upper = false;
            result.push(c);
        }
    }
    result
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::declaration::fragment_encoded;
    use crate::mirror_runtime::MirrorRuntime;
    use std::path::PathBuf;

    /// Helper: build a MirrorFragment from MirrorData and children.
    fn frag(data: MirrorData, children: Vec<MirrorFragment>) -> MirrorFragment {
        fragment_encoded(data, children)
    }

    // -------------------------------------------------------------------
    // Unit tests for helpers
    // -------------------------------------------------------------------

    #[test]
    fn to_pascal_case_snake() {
        assert_eq!(to_pascal_case("bias_tree"), "BiasTree");
    }

    #[test]
    fn to_pascal_case_kebab() {
        assert_eq!(to_pascal_case("bias-tree"), "BiasTree");
    }

    #[test]
    fn to_pascal_case_single() {
        assert_eq!(to_pascal_case("color"), "Color");
    }

    #[test]
    fn to_pascal_case_already() {
        assert_eq!(to_pascal_case("Color"), "Color");
    }

    #[test]
    fn to_snake_case_pascal() {
        assert_eq!(to_snake_case("BiasTree"), "bias_tree");
    }

    #[test]
    fn to_snake_case_already() {
        assert_eq!(to_snake_case("bias_tree"), "bias_tree");
    }

    #[test]
    fn to_snake_case_kebab() {
        assert_eq!(to_snake_case("bias-tree"), "bias_tree");
    }

    #[test]
    fn map_type_text() {
        assert_eq!(map_type("text"), "String");
    }

    #[test]
    fn map_type_nat() {
        assert_eq!(map_type("nat"), "u64");
    }

    #[test]
    fn map_type_option() {
        assert_eq!(map_type("option(text)"), "Option<String>");
    }

    #[test]
    fn map_type_result() {
        assert_eq!(map_type("result(text, error)"), "Result<String, Error>");
    }

    #[test]
    fn map_type_list() {
        assert_eq!(map_type("[text]"), "Vec<String>");
    }

    #[test]
    fn map_type_vec() {
        assert_eq!(map_type("vec(u32)"), "Vec<u32>");
    }

    #[test]
    fn map_type_imperfect() {
        assert_eq!(
            map_type("imperfect(observation, error, loss)"),
            "Imperfect<Observation, Error, Loss>"
        );
    }

    #[test]
    fn map_type_unknown() {
        assert_eq!(map_type("widget"), "Widget");
    }

    #[test]
    fn strip_grammar_prefix_at() {
        assert_eq!(strip_grammar_prefix("@test"), "test");
    }

    #[test]
    fn strip_grammar_prefix_path() {
        assert_eq!(strip_grammar_prefix("@code/rust"), "code_rust");
    }

    #[test]
    fn parse_field_with_type() {
        assert_eq!(
            parse_field("name: text"),
            Some(("name".to_string(), "text".to_string()))
        );
    }

    #[test]
    fn parse_field_no_type() {
        assert_eq!(parse_field("identity"), None);
    }

    // -------------------------------------------------------------------
    // Integration tests — compile .mirror source → Rust
    // -------------------------------------------------------------------

    #[test]
    fn emit_rust_simple_enum() {
        let runtime = MirrorRuntime::new();
        let compiled: Result<CompiledShatter, _> =
            runtime.compile_source("type color = red | blue").into();
        let compiled = compiled.unwrap();
        let rust = emit_rust(&compiled);
        assert!(rust.contains("pub enum Color"), "got:\n{}", rust);
        assert!(rust.contains("Red"), "got:\n{}", rust);
        assert!(rust.contains("Blue"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_unit_struct() {
        let runtime = MirrorRuntime::new();
        let compiled: Result<CompiledShatter, _> = runtime.compile_source("type point").into();
        let compiled = compiled.unwrap();
        let rust = emit_rust(&compiled);
        assert!(rust.contains("pub struct Point;"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_struct_with_fields() {
        let runtime = MirrorRuntime::new();
        let compiled: Result<CompiledShatter, _> = runtime
            .compile_source("type user {\n  name: text,\n  email: text,\n}")
            .into();
        let compiled = compiled.unwrap();
        let rust = emit_rust(&compiled);
        assert!(rust.contains("pub struct User"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_grammar_becomes_module() {
        let runtime = MirrorRuntime::new();
        let compiled: Result<CompiledShatter, _> = runtime
            .compile_source("grammar @test {\n  type x\n}")
            .into();
        let compiled = compiled.unwrap();
        let rust = emit_rust(&compiled);
        assert!(rust.contains("pub mod test"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_action_becomes_function() {
        let runtime = MirrorRuntime::new();
        let compiled: Result<CompiledShatter, _> =
            runtime.compile_source("action boot(identity)").into();
        let compiled = compiled.unwrap();
        let rust = emit_rust(&compiled);
        assert!(rust.contains("pub fn boot"), "got:\n{}", rust);
        assert!(rust.contains("todo!()"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_property_becomes_function() {
        let runtime = MirrorRuntime::new();
        let compiled: Result<CompiledShatter, _> = runtime
            .compile_source("property types_lowercase(grammar)")
            .into();
        let compiled = compiled.unwrap();
        let rust = emit_rust(&compiled);
        assert!(rust.contains("pub fn types_lowercase"), "got:\n{}", rust);
        assert!(rust.contains("PropertyError"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_parameterized_type() {
        let runtime = MirrorRuntime::new();
        let compiled: Result<CompiledShatter, _> =
            runtime.compile_source("type error(observation)").into();
        let compiled = compiled.unwrap();
        let rust = emit_rust(&compiled);
        assert!(
            rust.contains("Error") && (rust.contains("Observation") || rust.contains("struct")),
            "got:\n{}",
            rust
        );
    }

    #[test]
    fn emit_rust_from_boot_meta() {
        let runtime = MirrorRuntime::new();
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("boot/01-meta.mirror");
        let compiled = runtime.compile_file(&path).unwrap();
        let rust = emit_rust(&compiled);

        assert!(rust.contains("pub"), "meta must produce public items");
        assert!(!rust.is_empty(), "meta must produce some Rust");
    }

    #[test]
    fn emit_rust_from_boot_code_rust() {
        let runtime = MirrorRuntime::new();
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("boot/03a-code-rust.mirror");
        let compiled = runtime.compile_file(&path).unwrap();
        let rust = emit_rust(&compiled);

        assert!(
            rust.contains("pub mod") || rust.contains("pub struct") || rust.contains("pub fn"),
            "code/rust must produce public items, got:\n{}",
            rust
        );
    }

    #[test]
    fn emit_rust_header_present() {
        let runtime = MirrorRuntime::new();
        let compiled: Result<CompiledShatter, _> = runtime.compile_source("type x").into();
        let compiled = compiled.unwrap();
        let rust = emit_rust(&compiled);
        assert!(
            rust.starts_with("// Generated by mirror craft --target rust"),
            "should have header"
        );
    }

    #[test]
    fn emit_rust_fragment_api() {
        let data = MirrorData::new(
            DeclKind::Type,
            "widget",
            vec![],
            vec!["small".to_string(), "large".to_string()],
        );
        let fragment = frag(data, vec![]);
        let rust = emit_rust_fragment(&fragment);
        assert!(rust.contains("pub enum Widget"), "got:\n{}", rust);
        assert!(rust.contains("Small"), "got:\n{}", rust);
        assert!(rust.contains("Large"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_nested_grammar_types() {
        let inner_data = MirrorData::new(
            DeclKind::Type,
            "status",
            vec![],
            vec!["active".to_string(), "inactive".to_string()],
        );
        let inner = frag(inner_data, vec![]);
        let grammar_data = MirrorData::new(DeclKind::Grammar, "@test", vec![], vec![]);
        let grammar = frag(grammar_data, vec![inner]);
        let rust = emit_rust_fragment(&grammar);
        assert!(rust.contains("pub mod test"), "got:\n{}", rust);
        assert!(rust.contains("pub enum Status"), "got:\n{}", rust);
        assert!(rust.contains("Active"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_map_type_f64() {
        assert_eq!(map_type("f64"), "f64");
    }

    #[test]
    fn emit_rust_map_type_bool() {
        assert_eq!(map_type("bool"), "bool");
    }

    #[test]
    fn emit_rust_map_type_ref() {
        assert_eq!(map_type("ref"), "String");
    }

    #[test]
    fn emit_rust_map_type_oid() {
        assert_eq!(map_type("oid"), "Oid");
    }

    #[test]
    fn emit_rust_map_type_loss() {
        assert_eq!(map_type("loss"), "Loss");
    }

    #[test]
    fn emit_rust_map_type_hashmap() {
        assert_eq!(map_type("hashmap(text, u32)"), "HashMap<String, u32>");
    }
}
