//! emit_rust — Rust code emitter for compiled .mirror declarations.
//!
//! Crystal -> .rs files. Takes a `MirrorFragment` (or `CompiledShatter`)
//! and produces Rust source code.
//!
//! ## Mapping
//!
//! - `type color = red | blue`  ->  `pub enum Color { Red, Blue }`
//! - `type user { name: text }` ->  `pub struct User { pub name: String }`
//! - `type point`               ->  `pub struct Point;`
//! - `grammar @test { ... }`    ->  `pub mod test { ... }`
//! - `action boot(identity)`    ->  `pub fn boot(identity: Identity) { todo!() }`
//! - `property p(g) <= verdict` ->  `pub fn p(g: &Grammar) -> Verdict { todo!() }`

use crate::declaration::{MirrorFragment, MirrorFragmentExt};
use crate::mirror_ast::MirrorAST;
use crate::mirror_runtime::CompiledShatter;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Emit Rust source code from a compiled shatter artifact.
pub fn emit_rust(compiled: &CompiledShatter) -> String {
    emit_rust_fragment(&compiled.fragment)
}

/// Emit Rust source code from a MirrorAST node.
///
/// This is the canonical entry point: takes a typed AST and produces Rust code.
/// Inline children (e.g. FocusNode.children) are converted to fragment children.
pub fn emit_rust_ast(ast: &MirrorAST) -> String {
    use prism::MerkleTree;
    let child_frags: Vec<MirrorFragment> = ast
        .children()
        .iter()
        .map(|c| crate::declaration::fragment(c.clone(), vec![]))
        .collect();
    let frag = crate::declaration::fragment(ast.clone(), child_frags);
    emit_rust_fragment(&frag)
}

/// Emit Rust source code from a MirrorFragment.
pub fn emit_rust_fragment(frag: &MirrorFragment) -> String {
    let mut output = String::new();
    output.push_str("// Generated by mirror craft --target rust\n");
    output.push_str("// Do not edit \u{2014} this file is derived from .mirror source\n\n");

    emit_frag(frag, &mut output, 0);
    output
}

// ---------------------------------------------------------------------------
// Fragment dispatch
// ---------------------------------------------------------------------------

fn emit_frag(frag: &MirrorFragment, out: &mut String, indent: usize) {
    let ast = frag.mirror_ast();
    let tag = ast.decl_tag();
    match tag {
        "type" => emit_type(frag, out, indent),
        "grammar" => emit_module(frag, out, indent),
        "action" => emit_function(frag, out, indent),
        "property" => emit_property(frag, out, indent),
        "in" => { /* use statement -- skip for now */ }
        "out" => { /* pub export -- skip for now */ }
        "form" => emit_form_container(frag, out, indent),
        _ => {
            // Other kinds: emit as a comment
            write_indent(out, indent);
            out.push_str(&format!("// {}: {}\n", tag, ast.name()));
        }
    }
}

// ---------------------------------------------------------------------------
// Type emission
// ---------------------------------------------------------------------------

fn emit_type(frag: &MirrorFragment, out: &mut String, indent: usize) {
    let ast = frag.mirror_ast();
    let variants = ast.variants_as_strings();
    let params = ast.params_as_strings();
    let children = frag.mirror_children();
    let name = to_pascal_case(ast.name());

    if !variants.is_empty() {
        // Enum: `type color = red | blue`
        emit_enum(&variants, &name, out, indent);
    } else if has_typed_fields_frag(frag) {
        // Struct with fields: `type user { name: text, email: text }`
        emit_struct_with_fields(frag, &name, out, indent);
    } else if !params.is_empty() {
        // Parameterized type without variants or fields -- generic struct
        emit_generic_struct(&params, &name, out, indent);
    } else if !children.is_empty() {
        // Struct with child declarations (has block, but children are decls not fields)
        emit_struct_with_children(frag, &name, out, indent);
    } else {
        // Unit struct: `type point`
        write_indent(out, indent);
        out.push_str(&format!("pub struct {};\n", name));
    }
}

fn emit_enum(variants: &[String], name: &str, out: &mut String, indent: usize) {
    write_indent(out, indent);
    out.push_str(&format!("pub enum {} {{\n", name));
    for variant in variants {
        write_indent(out, indent + 1);
        out.push_str(&format!("{},\n", to_pascal_case(variant)));
    }
    write_indent(out, indent);
    out.push_str("}\n");
}

fn emit_struct_with_fields(frag: &MirrorFragment, name: &str, out: &mut String, indent: usize) {
    let ast = frag.mirror_ast();
    let params = ast.params_as_strings();
    let children = frag.mirror_children();

    // Extract subset relation if present
    let subset_ref = extract_subset_ref_frag(frag);

    write_indent(out, indent);
    out.push_str(&format!("pub struct {} {{\n", name));

    // Parse params as `name: type` pairs
    for param in &params {
        if let Some((field_name, field_type)) = parse_field(param) {
            write_indent(out, indent + 1);
            out.push_str(&format!(
                "pub {}: {},\n",
                to_snake_case(&field_name),
                map_type(&field_type)
            ));
        }
    }

    // Also check children for field-like declarations
    for child in children {
        let child_ast = child.mirror_ast();
        let child_tag = child_ast.decl_tag();
        if child_tag == "type" || child_tag == "binding" {
            let child_params = child_ast.params_as_strings();
            let child_variants = child_ast.variants_as_strings();
            // child.name is the field name, child.params[0] or child.variants[0] is the type
            let field_type = if !child_params.is_empty() {
                child_params[0].clone()
            } else if !child_variants.is_empty() {
                child_variants[0].clone()
            } else {
                continue;
            };
            write_indent(out, indent + 1);
            out.push_str(&format!(
                "pub {}: {},\n",
                to_snake_case(child_ast.name()),
                map_type(&field_type)
            ));
        }
    }

    write_indent(out, indent);
    out.push_str("}\n");

    // Emit From impl for subset relations
    if let Some(parent_type) = subset_ref {
        out.push('\n');
        write_indent(out, indent);
        let parent_name = to_pascal_case(&parent_type);
        out.push_str(&format!("impl From<{}> for {} {{\n", parent_name, name));
        write_indent(out, indent + 1);
        out.push_str(&format!("fn from(_value: {}) -> Self {{\n", parent_name));
        write_indent(out, indent + 2);
        out.push_str("todo!()\n");
        write_indent(out, indent + 1);
        out.push_str("}\n");
        write_indent(out, indent);
        out.push_str("}\n");
    }
}

fn emit_generic_struct(params: &[String], name: &str, out: &mut String, indent: usize) {
    write_indent(out, indent);
    let generics: Vec<String> = params.iter().map(|p| to_pascal_case(p)).collect();
    out.push_str(&format!("pub struct {}<{}>;\n", name, generics.join(", ")));
}

fn emit_struct_with_children(frag: &MirrorFragment, name: &str, out: &mut String, indent: usize) {
    // Type with children that aren't simple fields -- emit struct + nested items
    write_indent(out, indent);
    out.push_str(&format!("pub struct {};\n", name));

    // Emit child declarations
    for child in frag.mirror_children() {
        emit_frag(child, out, indent);
    }
}

// ---------------------------------------------------------------------------
// Grammar -> module
// ---------------------------------------------------------------------------

fn emit_module(frag: &MirrorFragment, out: &mut String, indent: usize) {
    let ast = frag.mirror_ast();
    let mod_name = strip_grammar_prefix(ast.name());
    write_indent(out, indent);
    out.push_str(&format!("pub mod {} {{\n", to_snake_case(&mod_name)));

    for child in frag.mirror_children() {
        emit_frag(child, out, indent + 1);
    }

    write_indent(out, indent);
    out.push_str("}\n");
}

// ---------------------------------------------------------------------------
// Action -> function
// ---------------------------------------------------------------------------

fn emit_function(frag: &MirrorFragment, out: &mut String, indent: usize) {
    let ast = frag.mirror_ast();
    let params = ast.params_as_strings();

    write_indent(out, indent);
    let fn_name = to_snake_case(ast.name());

    // Build parameter list
    let params_str = if params.is_empty() {
        String::new()
    } else {
        params
            .iter()
            .map(|p| {
                if let Some((name, typ)) = parse_field(p) {
                    format!("{}: {}", to_snake_case(&name), map_type(&typ))
                } else {
                    format!("{}: {}", to_snake_case(p), to_pascal_case(p))
                }
            })
            .collect::<Vec<_>>()
            .join(", ")
    };

    // Determine return type
    let return_type = if let Some(rt) = ast.return_type_str() {
        format!(" -> {}", map_type(&rt))
    } else {
        String::new()
    };

    out.push_str(&format!(
        "pub fn {}({}){} {{\n",
        fn_name, params_str, return_type
    ));
    write_indent(out, indent + 1);
    out.push_str("todo!()\n");
    write_indent(out, indent);
    out.push_str("}\n");
}

// ---------------------------------------------------------------------------
// Property -> function
// ---------------------------------------------------------------------------

fn emit_property(frag: &MirrorFragment, out: &mut String, indent: usize) {
    let ast = frag.mirror_ast();
    let params = ast.params_as_strings();

    write_indent(out, indent);
    let fn_name = to_snake_case(ast.name());

    let params_str = if params.is_empty() {
        String::new()
    } else {
        params
            .iter()
            .map(|p| {
                if let Some((name, typ)) = parse_field(p) {
                    format!("{}: &{}", to_snake_case(&name), to_pascal_case(&typ))
                } else {
                    format!("{}: &{}", to_snake_case(p), to_pascal_case(p))
                }
            })
            .collect::<Vec<_>>()
            .join(", ")
    };

    out.push_str(&format!(
        "pub fn {}({}) -> Imperfect<(), PropertyError, PropertyLoss> {{\n",
        fn_name, params_str
    ));
    write_indent(out, indent + 1);
    out.push_str("todo!()\n");
    write_indent(out, indent);
    out.push_str("}\n");
}

// ---------------------------------------------------------------------------
// Form container (top-level form @name { ... })
// ---------------------------------------------------------------------------

fn emit_form_container(frag: &MirrorFragment, out: &mut String, indent: usize) {
    let ast = frag.mirror_ast();
    let children = frag.mirror_children();
    // A top-level form acts like a module
    if ast.name().starts_with('@') || !children.is_empty() {
        let mod_name = strip_grammar_prefix(ast.name());
        if !mod_name.is_empty() {
            write_indent(out, indent);
            out.push_str(&format!("pub mod {} {{\n", to_snake_case(&mod_name)));
            for child in children {
                emit_frag(child, out, indent + 1);
            }
            write_indent(out, indent);
            out.push_str("}\n");
        } else {
            for child in children {
                emit_frag(child, out, indent);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn write_indent(out: &mut String, indent: usize) {
    for _ in 0..indent {
        out.push_str("    ");
    }
}

/// Check whether a fragment's params look like typed fields (`name: type`).
fn has_typed_fields_frag(frag: &MirrorFragment) -> bool {
    let ast = frag.mirror_ast();
    let params = ast.params_as_strings();
    let children = frag.mirror_children();
    params.iter().any(|p| p.contains(':'))
        || children.iter().any(|c| {
            let tag = c.mirror_ast().decl_tag();
            let cp = c.mirror_ast().params_as_strings();
            let cv = c.mirror_ast().variants_as_strings();
            (tag == "type" || tag == "binding")
                && (!cp.is_empty() || !cv.is_empty())
        })
}

/// Parse `"name: type"` -> `Some(("name", "type"))`, or `None` if no colon.
fn parse_field(s: &str) -> Option<(String, String)> {
    let parts: Vec<&str> = s.splitn(2, ':').collect();
    if parts.len() == 2 {
        Some((parts[0].trim().to_string(), parts[1].trim().to_string()))
    } else {
        None
    }
}

/// Extract a subset reference from a fragment's params.
///
/// Subset relations were tracked via OpticOp::Subset on Form, but forms
/// built from fragments always had empty optic_ops. Detect subset by
/// scanning params for `<ref` patterns directly.
fn extract_subset_ref_frag(frag: &MirrorFragment) -> Option<String> {
    let ast = frag.mirror_ast();
    let params = ast.params_as_strings();
    params
        .iter()
        .find(|p| p.starts_with('<'))
        .map(|p| p.trim_start_matches('<').trim().to_string())
}

/// Strip `@` prefix and path components for grammar names.
/// `@code/rust` -> `code_rust`, `@test` -> `test`.
fn strip_grammar_prefix(name: &str) -> String {
    let stripped = name.trim_start_matches('@');
    stripped.replace('/', "_")
}

/// Map a mirror type name to a Rust type.
fn map_type(mirror_type: &str) -> String {
    let t = mirror_type.trim();

    // Handle parameterized types: option(t), result(t, e), vec(t), etc.
    if let Some(idx) = t.find('(') {
        let base = &t[..idx];
        let inner = &t[idx + 1..t.len() - 1]; // strip parens
        let params: Vec<&str> = inner.split(',').map(|s| s.trim()).collect();
        let mapped_params: Vec<String> = params.iter().map(|p| map_type(p)).collect();

        return match base {
            "option" => format!("Option<{}>", mapped_params.join(", ")),
            "result" => format!("Result<{}>", mapped_params.join(", ")),
            "vec" => format!("Vec<{}>", mapped_params.join(", ")),
            "hashmap" => format!("HashMap<{}>", mapped_params.join(", ")),
            "imperfect" => format!("Imperfect<{}>", mapped_params.join(", ")),
            _ => format!("{}<{}>", to_pascal_case(base), mapped_params.join(", ")),
        };
    }

    // Handle list syntax: [t]
    if t.starts_with('[') && t.ends_with(']') {
        let inner = &t[1..t.len() - 1];
        return format!("Vec<{}>", map_type(inner));
    }

    // Primitive mappings
    match t {
        "text" | "string" => "String".to_string(),
        "nat" => "u64".to_string(),
        "f64" => "f64".to_string(),
        "f32" => "f32".to_string(),
        "u8" => "u8".to_string(),
        "u16" => "u16".to_string(),
        "u32" => "u32".to_string(),
        "u64" => "u64".to_string(),
        "usize" => "usize".to_string(),
        "i8" => "i8".to_string(),
        "i16" => "i16".to_string(),
        "i32" => "i32".to_string(),
        "i64" => "i64".to_string(),
        "bool" => "bool".to_string(),
        "str" => "&str".to_string(),
        "ref" => "String".to_string(),
        "oid" => "Oid".to_string(),
        "loss" => "Loss".to_string(),
        "prism" => "Prism".to_string(),
        "verdict" => "Verdict".to_string(),
        "imperfect" => "Imperfect<Crystal, Error, Loss>".to_string(),
        _ => to_pascal_case(t),
    }
}

/// Convert `snake_case` or `kebab-case` to `PascalCase`.
fn to_pascal_case(s: &str) -> String {
    s.split(['_', '-', '/'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => {
                    let mut s = first.to_uppercase().to_string();
                    s.extend(chars);
                    s
                }
            }
        })
        .collect()
}

/// Convert `PascalCase` or `kebab-case` to `snake_case`.
fn to_snake_case(s: &str) -> String {
    // If already snake_case or lowercase, return as-is (but replace hyphens and slashes)
    let s = s.replace(['-', '/'], "_");
    if s.chars()
        .all(|c| c.is_lowercase() || c == '_' || c.is_numeric())
    {
        return s;
    }

    let mut result = String::new();
    let mut prev_was_upper = false;
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 && !prev_was_upper {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
            prev_was_upper = true;
        } else {
            prev_was_upper = false;
            result.push(c);
        }
    }
    result
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mirror_runtime::MirrorRuntime;
    use std::path::PathBuf;

    // -------------------------------------------------------------------
    // Unit tests for helpers
    // -------------------------------------------------------------------

    #[test]
    fn to_pascal_case_snake() {
        assert_eq!(to_pascal_case("bias_tree"), "BiasTree");
    }

    #[test]
    fn to_pascal_case_kebab() {
        assert_eq!(to_pascal_case("bias-tree"), "BiasTree");
    }

    #[test]
    fn to_pascal_case_single() {
        assert_eq!(to_pascal_case("color"), "Color");
    }

    #[test]
    fn to_pascal_case_already() {
        assert_eq!(to_pascal_case("Color"), "Color");
    }

    #[test]
    fn to_snake_case_pascal() {
        assert_eq!(to_snake_case("BiasTree"), "bias_tree");
    }

    #[test]
    fn to_snake_case_already() {
        assert_eq!(to_snake_case("bias_tree"), "bias_tree");
    }

    #[test]
    fn to_snake_case_kebab() {
        assert_eq!(to_snake_case("bias-tree"), "bias_tree");
    }

    #[test]
    fn map_type_text() {
        assert_eq!(map_type("text"), "String");
    }

    #[test]
    fn map_type_nat() {
        assert_eq!(map_type("nat"), "u64");
    }

    #[test]
    fn map_type_option() {
        assert_eq!(map_type("option(text)"), "Option<String>");
    }

    #[test]
    fn map_type_result() {
        assert_eq!(map_type("result(text, error)"), "Result<String, Error>");
    }

    #[test]
    fn map_type_list() {
        assert_eq!(map_type("[text]"), "Vec<String>");
    }

    #[test]
    fn map_type_vec() {
        assert_eq!(map_type("vec(u32)"), "Vec<u32>");
    }

    #[test]
    fn map_type_imperfect() {
        assert_eq!(
            map_type("imperfect(observation, error, loss)"),
            "Imperfect<Observation, Error, Loss>"
        );
    }

    #[test]
    fn map_type_unknown() {
        assert_eq!(map_type("widget"), "Widget");
    }

    #[test]
    fn strip_grammar_prefix_at() {
        assert_eq!(strip_grammar_prefix("@test"), "test");
    }

    #[test]
    fn strip_grammar_prefix_path() {
        assert_eq!(strip_grammar_prefix("@code/rust"), "code_rust");
    }

    #[test]
    fn parse_field_with_type() {
        assert_eq!(
            parse_field("name: text"),
            Some(("name".to_string(), "text".to_string()))
        );
    }

    #[test]
    fn parse_field_no_type() {
        assert_eq!(parse_field("identity"), None);
    }

    // -------------------------------------------------------------------
    // Integration tests -- compile .mirror source -> Rust
    // -------------------------------------------------------------------

    #[test]
    fn emit_rust_simple_enum() {
        let runtime = MirrorRuntime::new();
        let compiled: Result<CompiledShatter, _> =
            runtime.compile_source("type color = red | blue").into();
        let compiled = compiled.unwrap();
        let rust = emit_rust(&compiled);
        assert!(rust.contains("pub enum Color"), "got:\n{}", rust);
        assert!(rust.contains("Red"), "got:\n{}", rust);
        assert!(rust.contains("Blue"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_unit_struct() {
        let runtime = MirrorRuntime::new();
        let compiled: Result<CompiledShatter, _> = runtime.compile_source("type point").into();
        let compiled = compiled.unwrap();
        let rust = emit_rust(&compiled);
        assert!(rust.contains("pub struct Point;"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_struct_with_fields() {
        let runtime = MirrorRuntime::new();
        let compiled: Result<CompiledShatter, _> = runtime
            .compile_source("type user {\n  name: text,\n  email: text,\n}")
            .into();
        let compiled = compiled.unwrap();
        let rust = emit_rust(&compiled);
        assert!(rust.contains("pub struct User"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_grammar_becomes_module() {
        let runtime = MirrorRuntime::new();
        let compiled: Result<CompiledShatter, _> = runtime
            .compile_source("grammar @test {\n  type x\n}")
            .into();
        let compiled = compiled.unwrap();
        let rust = emit_rust(&compiled);
        assert!(rust.contains("pub mod test"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_action_becomes_function() {
        let runtime = MirrorRuntime::new();
        let compiled: Result<CompiledShatter, _> =
            runtime.compile_source("action boot(identity)").into();
        let compiled = compiled.unwrap();
        let rust = emit_rust(&compiled);
        assert!(rust.contains("pub fn boot"), "got:\n{}", rust);
        assert!(rust.contains("todo!()"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_property_becomes_function() {
        let runtime = MirrorRuntime::new();
        let compiled: Result<CompiledShatter, _> = runtime
            .compile_source("property types_lowercase(grammar)")
            .into();
        let compiled = compiled.unwrap();
        let rust = emit_rust(&compiled);
        assert!(rust.contains("pub fn types_lowercase"), "got:\n{}", rust);
        assert!(rust.contains("PropertyError"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_parameterized_type() {
        let runtime = MirrorRuntime::new();
        let compiled: Result<CompiledShatter, _> =
            runtime.compile_source("type error(observation)").into();
        let compiled = compiled.unwrap();
        let rust = emit_rust(&compiled);
        assert!(
            rust.contains("Error") && (rust.contains("Observation") || rust.contains("struct")),
            "got:\n{}",
            rust
        );
    }

    #[test]
    fn emit_rust_from_boot_meta() {
        let runtime = MirrorRuntime::new();
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("boot/01-meta.mirror");
        let compiled = runtime.compile_file(&path).unwrap();
        let rust = emit_rust(&compiled);

        // Meta should produce types for pure, real, observation, etc.
        assert!(rust.contains("pub"), "meta must produce public items");
        assert!(!rust.is_empty(), "meta must produce some Rust");
    }

    #[test]
    fn emit_rust_from_boot_code_rust() {
        let runtime = MirrorRuntime::new();
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("boot/03a-code-rust.mirror");
        let compiled = runtime.compile_file(&path).unwrap();
        let rust = emit_rust(&compiled);

        // Should produce a module for @code/rust
        assert!(
            rust.contains("pub mod") || rust.contains("pub struct") || rust.contains("pub fn"),
            "code/rust must produce public items, got:\n{}",
            rust
        );
    }

    #[test]
    fn emit_rust_header_present() {
        let runtime = MirrorRuntime::new();
        let compiled: Result<CompiledShatter, _> = runtime.compile_source("type x").into();
        let compiled = compiled.unwrap();
        let rust = emit_rust(&compiled);
        assert!(
            rust.starts_with("// Generated by mirror craft --target rust"),
            "should have header"
        );
    }

    #[test]
    fn emit_rust_fragment_api() {
        // Test the emit_rust_fragment API directly
        use crate::mirror_runtime::parse_form;
        let frag = parse_form("type widget = small | large").ok().unwrap();
        let rust = emit_rust_fragment(&frag);
        assert!(rust.contains("pub enum Widget"), "got:\n{}", rust);
        assert!(rust.contains("Small"), "got:\n{}", rust);
        assert!(rust.contains("Large"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_nested_grammar_types() {
        use crate::mirror_runtime::parse_form;
        let frag: Result<_, _> = parse_form("grammar @test {\n  type status = active | inactive\n}").into();
        let frag = frag.unwrap();
        let rust = emit_rust_fragment(&frag);
        assert!(rust.contains("pub mod test"), "got:\n{}", rust);
        assert!(rust.contains("pub enum Status"), "got:\n{}", rust);
        assert!(rust.contains("Active"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_map_type_f64() {
        assert_eq!(map_type("f64"), "f64");
    }

    #[test]
    fn emit_rust_map_type_bool() {
        assert_eq!(map_type("bool"), "bool");
    }

    #[test]
    fn emit_rust_map_type_ref() {
        assert_eq!(map_type("ref"), "String");
    }

    #[test]
    fn emit_rust_map_type_oid() {
        assert_eq!(map_type("oid"), "Oid");
    }

    #[test]
    fn emit_rust_map_type_loss() {
        assert_eq!(map_type("loss"), "Loss");
    }

    #[test]
    fn emit_rust_map_type_hashmap() {
        assert_eq!(map_type("hashmap(text, u32)"), "HashMap<String, u32>");
    }

    // -------------------------------------------------------------------
    // emit_rust_ast -- typed AST to Rust code
    // -------------------------------------------------------------------

    #[test]
    fn emit_rust_ast_enum() {
        use crate::mirror_ast::{Identifier, SplitNode, TypeBody};
        let ast = MirrorAST::Split(SplitNode {
            name: Identifier::new("color"),
            variants: vec![],
            params: vec![],
            body: Some(TypeBody::Enum(vec![Identifier::new("red"), Identifier::new("blue")])),
            children: vec![],
        });
        let rust = emit_rust_ast(&ast);
        assert!(rust.contains("pub enum Color"), "got:\n{}", rust);
        assert!(rust.contains("Red"), "got:\n{}", rust);
        assert!(rust.contains("Blue"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_ast_action() {
        use crate::mirror_ast::{Field, Identifier, ZoomNode};
        let ast = MirrorAST::Zoom(ZoomNode {
            name: Identifier::new("boot"),
            params: vec![Field {
                name: Identifier::new("identity"),
                type_ref: Identifier::new("_"),
            }],
            target: None,
            grammar_ref: None,
            children: vec![],
            body: None,
        });
        let rust = emit_rust_ast(&ast);
        assert!(rust.contains("pub fn boot"), "got:\n{}", rust);
        assert!(rust.contains("todo!()"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_ast_grammar() {
        use crate::mirror_ast::{FocusNode, Identifier, SplitNode, TypeBody};
        let child = MirrorAST::Split(SplitNode {
            name: Identifier::new("status"),
            variants: vec![],
            params: vec![],
            body: Some(TypeBody::Enum(vec![Identifier::new("active"), Identifier::new("inactive")])),
            children: vec![],
        });
        let ast = MirrorAST::Focus(FocusNode {
            name: Identifier::new("@test"),
            target: None,
            children: vec![child],
        });
        let rust = emit_rust_ast(&ast);
        assert!(rust.contains("pub mod test"), "got:\n{}", rust);
        assert!(rust.contains("pub enum Status"), "got:\n{}", rust);
    }

    #[test]
    fn emit_rust_ast_matches_fragment_path() {
        // parse_ast -> emit_rust_ast should produce the same output as
        // parse_form -> emit_rust_fragment
        let source = "type widget = small | large";
        use crate::mirror_runtime::{parse_ast, parse_form};
        let ast = parse_ast(source).ok().unwrap();
        let frag = parse_form(source).ok().unwrap();
        let rust_ast = emit_rust_ast(&ast);
        let rust_frag = emit_rust_fragment(&frag);
        assert_eq!(rust_ast, rust_frag);
    }
}
