//! generate_crate — Generate Rust crate files from a SpecConfig target.
//!
//! Given a `TargetConfig` and compiled grammar fragments, generates:
//! - `Cargo.toml`
//! - `src/lib.rs` with Rust types derived from the grammars
//! - Optional per-grammar module files

use crate::declaration::MirrorFragment;
use crate::spec::TargetConfig;

// ---------------------------------------------------------------------------
// Output types
// ---------------------------------------------------------------------------

/// The output of crate generation: files ready to write to disk.
pub struct CrateOutput {
    /// Generated `Cargo.toml` content.
    pub cargo_toml: String,
    /// Generated `src/lib.rs` content.
    pub lib_rs: String,
    /// Additional module files: `(filename, content)`.
    pub modules: Vec<(String, String)>,
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

/// Generate a `Cargo.toml` from a target configuration.
pub fn generate_cargo_toml(target: &TargetConfig) -> String {
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

# Generated by mirror craft
# Do not edit — this file is derived from mirror.spec

[dependencies]
"#,
        name = target.name,
    )
}

/// Generate `src/lib.rs` from compiled grammar fragments.
pub fn generate_lib_rs(target: &TargetConfig, grammars: &[MirrorFragment]) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by mirror craft — target \"{}\"\n",
        target.name
    ));
    out.push_str("// Do not edit — this file is derived from .mirror source\n\n");

    if grammars.is_empty() {
        // Empty crate with just the grammars listed as comments
        for g in &target.grammars {
            out.push_str(&format!("// grammar: {}\n", g));
        }
    } else {
        // Emit Rust from each grammar fragment
        for frag in grammars {
            let rust = crate::emit_rust::emit_rust_fragment(frag);
            // Strip the emit_rust header (it adds its own) — we already have ours
            let body = strip_generated_header(&rust);
            out.push_str(body);
            out.push('\n');
        }
    }

    out
}

/// Generate a full crate from a target and its compiled grammars.
pub fn generate_crate(target: &TargetConfig, grammars: &[MirrorFragment]) -> CrateOutput {
    CrateOutput {
        cargo_toml: generate_cargo_toml(target),
        lib_rs: generate_lib_rs(target, grammars),
        modules: Vec::new(),
    }
}

/// Strip the "Generated by mirror craft" header that emit_rust adds,
/// since we add our own header in generate_lib_rs.
fn strip_generated_header(source: &str) -> &str {
    let mut pos = 0;
    for line in source.lines() {
        if line.starts_with("// Generated by") || line.starts_with("// Do not edit") {
            pos += line.len() + 1; // +1 for newline
        } else {
            break;
        }
    }
    // Skip any trailing blank line after the header
    if pos < source.len() && source.as_bytes().get(pos) == Some(&b'\n') {
        pos += 1;
    }
    &source[pos..]
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mirror_runtime::MirrorRuntime;
    use std::path::PathBuf;

    fn mirror_target() -> TargetConfig {
        TargetConfig {
            name: "mirror".into(),
            source: Some("boot".into()),
            lens: Some("@code/rust".into()),
            output_path: Some("rust/mirror/".into()),
            glob: None,
            grammars: vec!["@prism".into(), "@meta".into()],
        }
    }

    #[test]
    fn generate_cargo_toml_has_package_name() {
        let target = mirror_target();
        let toml = generate_cargo_toml(&target);
        assert!(toml.contains("name = \"mirror\""), "got:\n{}", toml);
    }

    #[test]
    fn generate_cargo_toml_has_dependencies() {
        let target = mirror_target();
        let toml = generate_cargo_toml(&target);
        assert!(toml.contains("[dependencies]"), "got:\n{}", toml);
    }

    #[test]
    fn generate_cargo_toml_has_edition() {
        let target = mirror_target();
        let toml = generate_cargo_toml(&target);
        assert!(toml.contains("edition = \"2021\""), "got:\n{}", toml);
    }

    #[test]
    fn generate_lib_rs_has_header() {
        let target = mirror_target();
        let lib = generate_lib_rs(&target, &[]);
        assert!(lib.contains("Generated by mirror craft"), "got:\n{}", lib);
    }

    #[test]
    fn generate_lib_rs_from_boot_prism() {
        let runtime = MirrorRuntime::new();
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("boot/00-prism.mirror");
        let compiled = runtime.compile_file(&path).unwrap();
        let target = mirror_target();

        let lib = generate_lib_rs(&target, &[compiled.fragment]);
        assert!(
            lib.contains("Generated by mirror craft"),
            "should have header, got:\n{}",
            lib
        );
        // Boot prism is structural — it produces comments, not pub items.
        // The emitter correctly renders what the grammar contains.
        assert!(!lib.is_empty(), "should produce non-empty output");
    }

    #[test]
    fn generate_lib_rs_from_boot_meta() {
        let runtime = MirrorRuntime::new();
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("boot/01-meta.mirror");
        let compiled = runtime.compile_file(&path).unwrap();
        let target = mirror_target();

        let lib = generate_lib_rs(&target, &[compiled.fragment]);
        assert!(
            lib.contains("pub"),
            "meta should produce pub items, got:\n{}",
            lib
        );
    }

    #[test]
    fn generate_crate_produces_both_files() {
        let target = mirror_target();
        let output = generate_crate(&target, &[]);
        assert!(!output.cargo_toml.is_empty());
        assert!(!output.lib_rs.is_empty());
    }
}
