// Generated by mirror craft boot
// Do not edit — this file is derived from boot grammars
//
// Bootstrap closure: parser compiles boot grammars -> codegen generates
// these Prism types -> parser resolves to these types by Oid -> fixed point.
//
// Regenerate: cargo test generate_bridge_module_from_boot -- --nocapture

// The derive macro expands to `prism_core::Addressable` / `prism_core::Oid`.
// In this crate, prism-core is imported as `prism`, so we alias it.
use prism as prism_core;
use prism::DerivePrism as Prism;
use prism::{Addressable, Oid};

use std::sync::LazyLock;

#[derive(Debug, Clone, Prism)]
#[oid("@prism")]
pub struct PrismGrammar;

#[derive(Debug, Clone, Prism)]
#[oid("@meta")]
pub struct MetaGrammar;

#[derive(Debug, Clone, Prism)]
#[oid("@code")]
pub struct CodeGrammar;

#[derive(Debug, Clone, Prism)]
#[oid("@code/rust")]
pub struct CodeRustGrammar;

#[derive(Debug, Clone, Prism)]
#[oid("@actor")]
pub struct ActorGrammar;

#[derive(Debug, Clone, Prism)]
#[oid("@runtime")]
pub struct RuntimeGrammar;

#[derive(Debug, Clone, Prism)]
#[oid("@property")]
pub struct PropertyGrammar;

#[derive(Debug, Clone, Prism)]
#[oid("@package")]
pub struct PackageGrammar;

#[derive(Debug, Clone, Prism)]
#[oid("@git")]
pub struct GitGrammar;

#[derive(Debug, Clone, Prism)]
#[oid("@mirror")]
pub struct MirrorGrammar;

#[derive(Debug, Clone, Prism)]
#[oid("@time")]
pub struct TimeGrammar;

// ---------------------------------------------------------------------------
// Grammar registry — lookup from name to Oid at zero parse cost
// ---------------------------------------------------------------------------

// Cached Oids — computed once via LazyLock, then O(1) clone.
static PRISM_OID: LazyLock<Oid> = LazyLock::new(|| PrismGrammar.oid());
static META_OID: LazyLock<Oid> = LazyLock::new(|| MetaGrammar.oid());
static CODE_OID: LazyLock<Oid> = LazyLock::new(|| CodeGrammar.oid());
static CODE_RUST_OID: LazyLock<Oid> = LazyLock::new(|| CodeRustGrammar.oid());
static ACTOR_OID: LazyLock<Oid> = LazyLock::new(|| ActorGrammar.oid());
static RUNTIME_OID: LazyLock<Oid> = LazyLock::new(|| RuntimeGrammar.oid());
static PROPERTY_OID: LazyLock<Oid> = LazyLock::new(|| PropertyGrammar.oid());
static PACKAGE_OID: LazyLock<Oid> = LazyLock::new(|| PackageGrammar.oid());
static GIT_OID: LazyLock<Oid> = LazyLock::new(|| GitGrammar.oid());
static MIRROR_OID: LazyLock<Oid> = LazyLock::new(|| MirrorGrammar.oid());
static TIME_OID: LazyLock<Oid> = LazyLock::new(|| TimeGrammar.oid());

/// All boot grammar Oids, keyed by name. O(1) lookup after first call, no parsing.
pub fn grammar_oid(name: &str) -> Option<Oid> {
    match name {
        "@prism" => Some(PRISM_OID.clone()),
        "@meta" => Some(META_OID.clone()),
        "@code" => Some(CODE_OID.clone()),
        "@code/rust" => Some(CODE_RUST_OID.clone()),
        "@actor" => Some(ACTOR_OID.clone()),
        "@runtime" => Some(RUNTIME_OID.clone()),
        "@property" => Some(PROPERTY_OID.clone()),
        "@package" => Some(PACKAGE_OID.clone()),
        "@git" => Some(GIT_OID.clone()),
        "@mirror" => Some(MIRROR_OID.clone()),
        "@time" => Some(TIME_OID.clone()),
        _ => None,
    }
}

/// All known grammar names in boot order.
pub const GRAMMAR_NAMES: &[&str] = &[
    "@prism",
    "@meta",
    "@code",
    "@code/rust",
    "@actor",
    "@runtime",
    "@property",
    "@package",
    "@git",
    "@mirror",
    "@time",
];

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use prism::Addressable;

    #[test]
    fn each_grammar_has_unique_oid() {
        let oids: Vec<Oid> = GRAMMAR_NAMES
            .iter()
            .map(|n| grammar_oid(n).unwrap())
            .collect();
        for (i, a) in oids.iter().enumerate() {
            for (j, b) in oids.iter().enumerate() {
                if i != j {
                    assert_ne!(
                        a, b,
                        "{} and {} must have different Oids",
                        GRAMMAR_NAMES[i], GRAMMAR_NAMES[j]
                    );
                }
            }
        }
    }

    #[test]
    fn grammar_oid_unknown_returns_none() {
        assert_eq!(grammar_oid("@unknown"), None);
    }

    #[test]
    fn grammar_oid_matches_derive() {
        // The grammar_oid function must return the same Oid as the derived struct
        assert_eq!(grammar_oid("@prism"), Some(PrismGrammar.oid()));
        assert_eq!(grammar_oid("@meta"), Some(MetaGrammar.oid()));
        assert_eq!(grammar_oid("@code/rust"), Some(CodeRustGrammar.oid()));
    }

    #[test]
    fn prism_grammar_display() {
        assert_eq!(format!("{}", PrismGrammar), "@prism");
        assert_eq!(format!("{}", MetaGrammar), "@meta");
        assert_eq!(format!("{}", CodeRustGrammar), "@code/rust");
    }

    #[test]
    fn grammar_oid_deterministic() {
        let a = PrismGrammar.oid();
        let b = PrismGrammar.oid();
        assert_eq!(a, b);
    }

    #[test]
    fn grammar_oid_not_dark() {
        for name in GRAMMAR_NAMES {
            let oid = grammar_oid(name).unwrap();
            assert!(!oid.is_dark(), "{} should not have dark oid", name);
        }
    }

    #[test]
    fn parser_oid_vs_generated_oid() {
        use crate::declaration::MirrorFragmentExt;
        use crate::mirror_runtime::MirrorRuntime;

        let runtime = MirrorRuntime::new();
        let src = std::fs::read_to_string(
            std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("boot/00-prism.mirror"),
        )
        .unwrap();
        let compiled = Result::from(runtime.compile_source(&src)).unwrap();
        let parser_oid = format!("{:?}", MirrorFragmentExt::oid(&compiled.fragment));
        let generated_oid = format!("{}", PrismGrammar.oid());

        eprintln!("parser oid:    {}", parser_oid);
        eprintln!("generated oid: {}", generated_oid);

        // These are DIFFERENT by design:
        // - parser_oid is content-addressed (hash of MirrorData bytes)
        // - generated_oid is name-addressed (hash of "@prism" string)
        // The bridge: grammar_oid("@prism") gives the name-addressed Oid
        // for O(1) lookup. The content-addressed Oid is what the store uses.
        // Both are valid identities for the same grammar — different projections.
        assert_ne!(
            parser_oid, generated_oid,
            "parser oid is content-addressed, generated oid is name-addressed — they should differ"
        );
    }

    #[test]
    fn benchmark_cached_oid_lookup() {
        // Warm up the LazyLock
        let _ = grammar_oid("@prism");

        let start = std::time::Instant::now();
        for _ in 0..100_000 {
            let _ = grammar_oid("@prism");
        }
        let elapsed = start.elapsed();
        eprintln!(
            "--- cached grammar_oid x100k: {:?} ({:?}/call) ---",
            elapsed,
            elapsed / 100_000
        );

        // Compare to parsing
        use crate::mirror_runtime::MirrorRuntime;
        let runtime = MirrorRuntime::new();
        let src = std::fs::read_to_string(
            std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("boot/00-prism.mirror"),
        )
        .unwrap();
        let start2 = std::time::Instant::now();
        for _ in 0..100 {
            let _ = runtime.compile_source(&src);
        }
        let elapsed2 = start2.elapsed();
        eprintln!(
            "--- parse 00-prism.mirror x100: {:?} ({:?}/call) ---",
            elapsed2,
            elapsed2 / 100
        );
        let cached_ns = elapsed.as_nanos() as f64 / 100_000.0;
        let parse_ns = elapsed2.as_nanos() as f64 / 100.0;
        eprintln!("--- speedup: {:.0}x ---", parse_ns / cached_ns);
    }
}
