//! generate_crate — Generate Rust crate files from a SpecConfig target.
//!
//! Given a `TargetConfig` and compiled grammar fragments, generates:
//! - `Cargo.toml`
//! - `src/lib.rs` with Rust types derived from the grammars
//! - Optional per-grammar module files

use crate::declaration::MirrorFragment;
use crate::spec::TargetConfig;

// ---------------------------------------------------------------------------
// Output types
// ---------------------------------------------------------------------------

/// The output of crate generation: files ready to write to disk.
pub struct CrateOutput {
    /// Generated `Cargo.toml` content.
    pub cargo_toml: String,
    /// Generated `src/lib.rs` content.
    pub lib_rs: String,
    /// Additional module files: `(filename, content)`.
    pub modules: Vec<(String, String)>,
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

/// Generate a `Cargo.toml` from a target configuration.
pub fn generate_cargo_toml(target: &TargetConfig) -> String {
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

# Generated by mirror craft
# Do not edit — this file is derived from mirror.spec

[dependencies]
"#,
        name = target.name,
    )
}

/// Generate `src/lib.rs` from compiled grammar fragments.
pub fn generate_lib_rs(target: &TargetConfig, grammars: &[MirrorFragment]) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by mirror craft — target \"{}\"\n",
        target.name
    ));
    out.push_str("// Do not edit — this file is derived from .mirror source\n\n");

    if grammars.is_empty() {
        // Empty crate with just the grammars listed as comments
        for g in &target.grammars {
            out.push_str(&format!("// grammar: {}\n", g));
        }
    } else {
        // Emit Rust from each grammar fragment
        for frag in grammars {
            let rust = crate::emit_rust::emit_rust_fragment(frag);
            // Strip the emit_rust header (it adds its own) — we already have ours
            let body = strip_generated_header(&rust);
            out.push_str(body);
            out.push('\n');
        }
    }

    out
}

/// Generate a full crate from a target and its compiled grammars.
pub fn generate_crate(target: &TargetConfig, grammars: &[MirrorFragment]) -> CrateOutput {
    CrateOutput {
        cargo_toml: generate_cargo_toml(target),
        lib_rs: generate_lib_rs(target, grammars),
        modules: Vec::new(),
    }
}

/// Generate a bridge module: Prism-derived structs for each grammar in boot.
///
/// Each grammar `@X` becomes a unit struct `XGrammar` with `#[derive(Prism)]`
/// and `#[oid("@X")]`. These types close the bootstrap loop: the parser
/// compiles boot grammars, the codegen generates Prism types from them,
/// and the parser can resolve to those types by Oid.
pub fn generate_bridge_module(grammars: &[MirrorFragment]) -> String {
    let mut out = String::new();
    out.push_str("// Generated by mirror craft boot\n");
    out.push_str("// Do not edit — this file is derived from boot grammars\n\n");
    out.push_str("use prism as prism_core;\n");
    out.push_str("use prism::{Addressable, Oid};\n");
    out.push_str("use prism::DerivePrism as Prism;\n\n");
    out.push_str("use std::sync::LazyLock;\n\n");

    let mut names: Vec<&str> = Vec::new();
    collect_grammar_names_from_fragments(grammars, &mut names);
    // Deduplicate while preserving order
    let mut seen = std::collections::HashSet::new();
    names.retain(|n| seen.insert(*n));

    for name in &names {
        let struct_name = grammar_name_to_struct(name);
        out.push_str("#[derive(Debug, Clone, Prism)]\n");
        out.push_str(&format!("#[oid(\"{}\")]\n", name));
        out.push_str(&format!("pub struct {};\n\n", struct_name));
    }

    // Emit cached LazyLock statics
    out.push_str("// Cached Oids — computed once via LazyLock, then O(1) clone.\n");
    for name in &names {
        let struct_name = grammar_name_to_struct(name);
        let static_name = grammar_name_to_static(name);
        out.push_str(&format!(
            "static {}: LazyLock<Oid> = LazyLock::new(|| {}.oid());\n",
            static_name, struct_name
        ));
    }
    out.push('\n');

    // Emit grammar_oid lookup function
    out.push_str("/// All boot grammar Oids, keyed by name. O(1) lookup after first call.\n");
    out.push_str("pub fn grammar_oid(name: &str) -> Option<Oid> {\n");
    out.push_str("    match name {\n");
    for name in &names {
        let static_name = grammar_name_to_static(name);
        out.push_str(&format!(
            "        \"{}\" => Some({}.clone()),\n",
            name, static_name
        ));
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // Emit GRAMMAR_NAMES constant
    out.push_str("/// All known grammar names in boot order.\n");
    out.push_str("pub const GRAMMAR_NAMES: &[&str] = &[\n");
    for name in &names {
        out.push_str(&format!("    \"{}\",\n", name));
    }
    out.push_str("];\n");

    out
}

/// Recursively collect grammar names (starting with `@`) from fragment trees.
fn collect_grammar_names_from_fragments<'a>(
    fragments: &'a [MirrorFragment],
    names: &mut Vec<&'a str>,
) {
    use crate::declaration::MirrorFragmentExt;
    for frag in fragments {
        let data = frag.mirror_data();
        // Skip bare `@` — it's a structural reference, not a grammar name
        if data.name.starts_with('@') && data.name.len() > 1 {
            names.push(&data.name);
        }
        collect_grammar_names_from_fragments(frag.mirror_children(), names);
    }
}

/// Convert a grammar name like `@code/rust` to a struct name like `CodeRustGrammar`.
fn grammar_name_to_struct(name: &str) -> String {
    let stripped = name.trim_start_matches('@');
    let pascal = stripped
        .split(['/', '_', '-'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => {
                    let mut s = first.to_uppercase().to_string();
                    s.extend(chars);
                    s
                }
            }
        })
        .collect::<String>();
    format!("{}Grammar", pascal)
}

/// Convert a grammar name like `@code/rust` to a static name like `CODE_RUST_OID`.
fn grammar_name_to_static(name: &str) -> String {
    let stripped = name.trim_start_matches('@');
    let upper = stripped.replace(['/', '-'], "_").to_uppercase();
    format!("{}_OID", upper)
}

/// Strip the "Generated by mirror craft" header that emit_rust adds,
/// since we add our own header in generate_lib_rs.
fn strip_generated_header(source: &str) -> &str {
    let mut pos = 0;
    for line in source.lines() {
        if line.starts_with("// Generated by") || line.starts_with("// Do not edit") {
            pos += line.len() + 1; // +1 for newline
        } else {
            break;
        }
    }
    // Skip any trailing blank line after the header
    if pos < source.len() && source.as_bytes().get(pos) == Some(&b'\n') {
        pos += 1;
    }
    &source[pos..]
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mirror_runtime::MirrorRuntime;
    use std::path::PathBuf;

    fn mirror_target() -> TargetConfig {
        TargetConfig {
            name: "mirror".into(),
            source: Some("boot".into()),
            lens: Some("@code/rust".into()),
            output_path: Some("rust/mirror/".into()),
            glob: None,
            grammars: vec!["@prism".into(), "@meta".into()],
        }
    }

    #[test]
    fn generate_cargo_toml_has_package_name() {
        let target = mirror_target();
        let toml = generate_cargo_toml(&target);
        assert!(toml.contains("name = \"mirror\""), "got:\n{}", toml);
    }

    #[test]
    fn generate_cargo_toml_has_dependencies() {
        let target = mirror_target();
        let toml = generate_cargo_toml(&target);
        assert!(toml.contains("[dependencies]"), "got:\n{}", toml);
    }

    #[test]
    fn generate_cargo_toml_has_edition() {
        let target = mirror_target();
        let toml = generate_cargo_toml(&target);
        assert!(toml.contains("edition = \"2021\""), "got:\n{}", toml);
    }

    #[test]
    fn generate_lib_rs_has_header() {
        let target = mirror_target();
        let lib = generate_lib_rs(&target, &[]);
        assert!(lib.contains("Generated by mirror craft"), "got:\n{}", lib);
    }

    #[test]
    fn generate_lib_rs_from_boot_prism() {
        let runtime = MirrorRuntime::new();
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("boot/00-prism.mirror");
        let compiled = runtime.compile_file(&path).unwrap();
        let target = mirror_target();

        let lib = generate_lib_rs(&target, &[compiled.fragment]);
        assert!(
            lib.contains("Generated by mirror craft"),
            "should have header, got:\n{}",
            lib
        );
        // Boot prism is structural — it produces comments, not pub items.
        // The emitter correctly renders what the grammar contains.
        assert!(!lib.is_empty(), "should produce non-empty output");
    }

    #[test]
    fn generate_lib_rs_from_boot_meta() {
        let runtime = MirrorRuntime::new();
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("boot/01-meta.mirror");
        let compiled = runtime.compile_file(&path).unwrap();
        let target = mirror_target();

        let lib = generate_lib_rs(&target, &[compiled.fragment]);
        assert!(
            lib.contains("pub"),
            "meta should produce pub items, got:\n{}",
            lib
        );
    }

    #[test]
    fn generate_crate_produces_both_files() {
        let target = mirror_target();
        let output = generate_crate(&target, &[]);
        assert!(!output.cargo_toml.is_empty());
        assert!(!output.lib_rs.is_empty());
    }

    // -----------------------------------------------------------------------
    // Bridge module generation — bootstrap closure
    // -----------------------------------------------------------------------

    fn boot_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("boot")
    }

    fn tempdir_for_test(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("mirror-test-{}-{}", name, std::process::id()));
        let _ = std::fs::create_dir_all(&dir);
        dir
    }

    #[test]
    fn generate_bridge_module_from_boot() {
        let runtime = MirrorRuntime::new();
        let store = tempdir_for_test("gen_bridge");
        let boot = runtime.compile_boot_dir(&boot_dir(), &store).unwrap();

        let fragments: Vec<_> = boot.resolved.values().map(|c| c.fragment.clone()).collect();

        let bridge = generate_bridge_module(&fragments);

        eprintln!("--- bridge module ---");
        eprintln!("{}", bridge);
        eprintln!("---");

        // Must contain derive(Prism) for each grammar
        assert!(
            bridge.contains("#[derive(Debug, Clone, Prism)]"),
            "must have derive, got:\n{}",
            bridge
        );
        assert!(
            bridge.contains("#[oid(\"@meta\")]"),
            "must have @meta oid, got:\n{}",
            bridge
        );
        assert!(
            bridge.contains("pub struct MetaGrammar;"),
            "must have MetaGrammar, got:\n{}",
            bridge
        );

        // Cleanup
        let _ = std::fs::remove_dir_all(&store);
    }

    #[test]
    fn generate_bridge_module_contains_all_boot_grammars() {
        let runtime = MirrorRuntime::new();
        let store = tempdir_for_test("gen_bridge_all");
        let boot = runtime.compile_boot_dir(&boot_dir(), &store).unwrap();

        let fragments: Vec<_> = boot.resolved.values().map(|c| c.fragment.clone()).collect();

        let bridge = generate_bridge_module(&fragments);

        // These grammars should all appear from the boot directory
        let expected_grammars = ["@meta", "@code/rust", "@property", "@actor"];
        for g in &expected_grammars {
            assert!(
                bridge.contains(&format!("#[oid(\"{}\")]", g)),
                "bridge must contain {}, got:\n{}",
                g,
                bridge
            );
        }

        let _ = std::fs::remove_dir_all(&store);
    }

    #[test]
    fn grammar_name_to_struct_simple() {
        assert_eq!(grammar_name_to_struct("@meta"), "MetaGrammar");
    }

    #[test]
    fn grammar_name_to_struct_path() {
        assert_eq!(grammar_name_to_struct("@code/rust"), "CodeRustGrammar");
    }

    #[test]
    fn grammar_name_to_struct_kebab() {
        assert_eq!(grammar_name_to_struct("@meta-action"), "MetaActionGrammar");
    }

    #[test]
    fn grammar_name_to_static_simple() {
        assert_eq!(grammar_name_to_static("@meta"), "META_OID");
    }

    #[test]
    fn grammar_name_to_static_path() {
        assert_eq!(grammar_name_to_static("@code/rust"), "CODE_RUST_OID");
    }

    #[test]
    fn bridge_module_has_grammar_oid_fn() {
        let runtime = MirrorRuntime::new();
        let store = tempdir_for_test("gen_bridge_fn");
        let boot = runtime.compile_boot_dir(&boot_dir(), &store).unwrap();

        let fragments: Vec<_> = boot.resolved.values().map(|c| c.fragment.clone()).collect();

        let bridge = generate_bridge_module(&fragments);
        assert!(
            bridge.contains("pub fn grammar_oid("),
            "must have grammar_oid function"
        );
        assert!(
            bridge.contains("LazyLock<Oid>"),
            "must have cached LazyLock statics"
        );
        assert!(
            bridge.contains("GRAMMAR_NAMES"),
            "must have GRAMMAR_NAMES constant"
        );

        let _ = std::fs::remove_dir_all(&store);
    }

    #[test]
    fn generated_bridge_compiles_as_rust() {
        // The generated bridge should be valid Rust syntax (basic check)
        let runtime = MirrorRuntime::new();
        let store = tempdir_for_test("gen_bridge_syntax");
        let boot = runtime.compile_boot_dir(&boot_dir(), &store).unwrap();

        let fragments: Vec<_> = boot.resolved.values().map(|c| c.fragment.clone()).collect();

        let bridge = generate_bridge_module(&fragments);

        // Every line should be a valid Rust construct or comment/blank
        for line in bridge.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty()
                || trimmed.starts_with("//")
                || trimmed.starts_with("use ")
                || trimmed.starts_with("static ")
                || trimmed.starts_with("pub fn ")
                || trimmed.starts_with("pub const ")
                || trimmed.starts_with("match ")
                || trimmed.starts_with('"')
                || trimmed.starts_with("_ =>")
                || trimmed == "}"
                || trimmed == "})"
                || trimmed == "];"
            {
                continue;
            }
            assert!(
                trimmed.starts_with("#[") || trimmed.starts_with("pub struct"),
                "unexpected line in bridge: {:?}",
                line
            );
        }

        let _ = std::fs::remove_dir_all(&store);
    }
}
