//! generate_crate — Generate Rust crate files from a SpecConfig target.
//!
//! Given a `TargetConfig` and compiled grammar fragments, generates:
//! - `Cargo.toml`
//! - `src/lib.rs` with Rust types derived from the grammars
//! - Optional per-grammar module files

use crate::declaration::MirrorFragment;
use crate::spec::TargetConfig;

// ---------------------------------------------------------------------------
// Output types
// ---------------------------------------------------------------------------

/// The output of crate generation: files ready to write to disk.
pub struct CrateOutput {
    /// Generated `Cargo.toml` content.
    pub cargo_toml: String,
    /// Generated `src/lib.rs` content.
    pub lib_rs: String,
    /// Additional module files: `(filename, content)`.
    pub modules: Vec<(String, String)>,
}

// ---------------------------------------------------------------------------
// Generation — stubs
// ---------------------------------------------------------------------------

/// Generate a `Cargo.toml` from a target configuration.
pub fn generate_cargo_toml(_target: &TargetConfig) -> String {
    todo!("generate_cargo_toml not yet implemented")
}

/// Generate `src/lib.rs` from compiled grammar fragments.
pub fn generate_lib_rs(_target: &TargetConfig, _grammars: &[MirrorFragment]) -> String {
    todo!("generate_lib_rs not yet implemented")
}

/// Generate a full crate from a target and its compiled grammars.
pub fn generate_crate(_target: &TargetConfig, _grammars: &[MirrorFragment]) -> CrateOutput {
    todo!("generate_crate not yet implemented")
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mirror_runtime::MirrorRuntime;
    use std::path::PathBuf;

    fn mirror_target() -> TargetConfig {
        TargetConfig {
            name: "mirror".into(),
            source: Some("boot".into()),
            lens: Some("@code/rust".into()),
            output_path: Some("rust/mirror/".into()),
            glob: None,
            grammars: vec!["@prism".into(), "@meta".into()],
        }
    }

    #[test]
    fn generate_cargo_toml_has_package_name() {
        let target = mirror_target();
        let toml = generate_cargo_toml(&target);
        assert!(toml.contains("name = \"mirror\""), "got:\n{}", toml);
    }

    #[test]
    fn generate_cargo_toml_has_dependencies() {
        let target = mirror_target();
        let toml = generate_cargo_toml(&target);
        assert!(toml.contains("[dependencies]"), "got:\n{}", toml);
    }

    #[test]
    fn generate_cargo_toml_has_edition() {
        let target = mirror_target();
        let toml = generate_cargo_toml(&target);
        assert!(toml.contains("edition = \"2021\""), "got:\n{}", toml);
    }

    #[test]
    fn generate_lib_rs_has_header() {
        let target = mirror_target();
        let lib = generate_lib_rs(&target, &[]);
        assert!(
            lib.contains("Generated by mirror craft"),
            "got:\n{}",
            lib
        );
    }

    #[test]
    fn generate_lib_rs_from_boot_prism() {
        let runtime = MirrorRuntime::new();
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("boot/00-prism.mirror");
        let compiled = runtime.compile_file(&path).unwrap();
        let target = mirror_target();

        let lib = generate_lib_rs(&target, &[compiled.fragment]);
        assert!(lib.contains("pub"), "prism should produce pub items, got:\n{}", lib);
    }

    #[test]
    fn generate_crate_produces_both_files() {
        let target = mirror_target();
        let output = generate_crate(&target, &[]);
        assert!(!output.cargo_toml.is_empty());
        assert!(!output.lib_rs.is_empty());
    }
}
