//! Generate `.mirror` grammar files from parsed tree-sitter node types
//! and LSP capabilities.

use super::language::{LanguageConfig, LspCapabilities};
use super::node_types::NodeType;

/// Generate a `.mirror` grammar file from node types and LSP capabilities.
pub fn generate_grammar(
    config: &LanguageConfig,
    node_types: &[NodeType],
    capabilities: &LspCapabilities,
) -> String {
    let mut out = String::new();

    // Header comment.
    let lsp_name = config
        .lsp_command
        .first()
        .map(|s| s.as_str())
        .unwrap_or("none");
    out.push_str(&format!(
        "-- auto-generated by: mirror lsp learn @code/{}\n",
        config.name
    ));
    out.push_str(&format!("-- tree-sitter: {}\n", config.tree_sitter));
    out.push_str(&format!("-- lsp: {}\n", lsp_name));
    out.push('\n');

    // Preamble.
    out.push_str("in @code\n\n");
    out.push_str(&format!("grammar @code/{} {{\n", config.name));

    // Emit types: leaves first, then sum types, then product types.
    let mut leaves: Vec<&NodeType> = Vec::new();
    let mut sums: Vec<&NodeType> = Vec::new();
    let mut products: Vec<&NodeType> = Vec::new();

    for nt in node_types {
        match nt {
            NodeType::Leaf { .. } => leaves.push(nt),
            NodeType::Sum { .. } => sums.push(nt),
            NodeType::Product { .. } => products.push(nt),
        }
    }

    if !leaves.is_empty() {
        out.push_str("\n    -- leaf types\n");
        for leaf in &leaves {
            out.push_str(&format!("    type {}\n", leaf.display_name()));
        }
    }

    if !sums.is_empty() {
        out.push_str("\n    -- sum types\n");
        for sum in &sums {
            if let NodeType::Sum { subtypes, .. } = sum {
                let display = sum.display_name();
                let alts: Vec<&str> = subtypes.iter().map(|s| strip_underscore(s)).collect();
                out.push_str(&format!("    type {} = {}\n", display, alts.join(" | ")));
            }
        }
    }

    if !products.is_empty() {
        out.push_str("\n    -- product types\n");
        for prod in &products {
            if let NodeType::Product { fields, .. } = prod {
                let display = prod.display_name();
                if fields.is_empty() {
                    out.push_str(&format!("    type {}\n", display));
                } else {
                    let field_strs: Vec<String> = fields
                        .iter()
                        .map(|f| {
                            let type_str = format_field_type(f);
                            format!("{}: {}", f.name, type_str)
                        })
                        .collect();
                    out.push_str(&format!(
                        "    type {} {{ {} }}\n",
                        display,
                        field_strs.join(", ")
                    ));
                }
            }
        }
    }

    // Emit LSP actions.
    let actions = capabilities.actions();
    if !actions.is_empty() {
        out.push_str("\n    -- lsp actions\n");
        for (_name, sig) in &actions {
            out.push_str(&format!(
                "    action {} in @code/{} {{ }}\n",
                sig, config.name
            ));
        }
    }

    // Emit commented-out actions for missing capabilities.
    let all_actions = LspCapabilities::all().actions();
    let present: Vec<&str> = actions.iter().map(|(n, _)| *n).collect();
    let missing: Vec<(&str, &str)> = all_actions
        .iter()
        .filter(|(n, _)| !present.contains(n))
        .copied()
        .collect();
    if !missing.is_empty() {
        out.push_str("\n    -- not supported by server\n");
        for (_name, sig) in &missing {
            out.push_str(&format!(
                "    -- action {} in @code/{} {{ }}\n",
                sig, config.name
            ));
        }
    }

    out.push_str("}\n\n");
    out.push_str(&format!("out @code/{}\n", config.name));

    out
}

/// Format the type of a field, handling multiple and optional modifiers.
fn format_field_type(field: &super::node_types::NodeField) -> String {
    let base = if field.types.len() == 1 {
        strip_underscore(&field.types[0]).to_string()
    } else {
        let alts: Vec<&str> = field.types.iter().map(|s| strip_underscore(s)).collect();
        format!("({})", alts.join(" | "))
    };

    let typed = if field.multiple {
        format!("[{}]", base)
    } else {
        base
    };

    if field.required {
        typed
    } else {
        format!("option({})", typed)
    }
}

/// Strip leading underscore from hidden supertypes.
fn strip_underscore(s: &str) -> &str {
    s.strip_prefix('_').unwrap_or(s)
}

#[cfg(test)]
mod tests {
    use super::super::language::LanguageConfig;
    use super::super::node_types::{NodeField, NodeType};
    use super::*;

    fn python_config() -> LanguageConfig {
        LanguageConfig {
            name: "python".into(),
            tree_sitter: "tree-sitter-python".into(),
            lsp_command: vec!["pyright-langserver".into(), "--stdio".into()],
            file_extensions: vec![".py".into()],
        }
    }

    #[test]
    fn generate_empty() {
        let config = python_config();
        let grammar = generate_grammar(&config, &[], &LspCapabilities::default());
        assert!(grammar.contains("grammar @code/python"));
        assert!(grammar.contains("in @code"));
        assert!(grammar.contains("out @code/python"));
        assert!(grammar.contains("-- auto-generated"));
    }

    #[test]
    fn generate_header_comment() {
        let config = python_config();
        let grammar = generate_grammar(&config, &[], &LspCapabilities::default());
        assert!(grammar.contains("-- tree-sitter: tree-sitter-python"));
        assert!(grammar.contains("-- lsp: pyright-langserver"));
    }

    #[test]
    fn generate_leaf_types() {
        let config = python_config();
        let types = vec![
            NodeType::Leaf {
                name: "identifier".into(),
            },
            NodeType::Leaf {
                name: "string".into(),
            },
        ];
        let grammar = generate_grammar(&config, &types, &LspCapabilities::default());
        assert!(grammar.contains("    type identifier\n"));
        assert!(grammar.contains("    type string\n"));
    }

    #[test]
    fn generate_sum_type() {
        let config = python_config();
        let types = vec![NodeType::Sum {
            name: "_expression".into(),
            subtypes: vec!["call".into(), "identifier".into()],
        }];
        let grammar = generate_grammar(&config, &types, &LspCapabilities::default());
        assert!(grammar.contains("    type expression = call | identifier\n"));
    }

    #[test]
    fn generate_product_type() {
        let config = python_config();
        let types = vec![NodeType::Product {
            name: "function_definition".into(),
            fields: vec![
                NodeField {
                    name: "body".into(),
                    multiple: false,
                    required: true,
                    types: vec!["block".into()],
                },
                NodeField {
                    name: "name".into(),
                    multiple: false,
                    required: true,
                    types: vec!["identifier".into()],
                },
            ],
            children: vec![],
        }];
        let grammar = generate_grammar(&config, &types, &LspCapabilities::default());
        assert!(grammar.contains("type function_definition { body: block, name: identifier }"));
    }

    #[test]
    fn generate_optional_field() {
        let config = python_config();
        let types = vec![NodeType::Product {
            name: "function_definition".into(),
            fields: vec![NodeField {
                name: "return_type".into(),
                multiple: false,
                required: false,
                types: vec!["type".into()],
            }],
            children: vec![],
        }];
        let grammar = generate_grammar(&config, &types, &LspCapabilities::default());
        assert!(grammar.contains("return_type: option(type)"));
    }

    #[test]
    fn generate_multiple_field() {
        let config = python_config();
        let types = vec![NodeType::Product {
            name: "block".into(),
            fields: vec![NodeField {
                name: "statements".into(),
                multiple: true,
                required: true,
                types: vec!["statement".into()],
            }],
            children: vec![],
        }];
        let grammar = generate_grammar(&config, &types, &LspCapabilities::default());
        assert!(grammar.contains("statements: [statement]"));
    }

    #[test]
    fn generate_union_field_type() {
        let config = python_config();
        let types = vec![NodeType::Product {
            name: "argument_list".into(),
            fields: vec![NodeField {
                name: "children".into(),
                multiple: true,
                required: true,
                types: vec!["expression".into(), "keyword_argument".into()],
            }],
            children: vec![],
        }];
        let grammar = generate_grammar(&config, &types, &LspCapabilities::default());
        assert!(grammar.contains("children: [(expression | keyword_argument)]"));
    }

    #[test]
    fn generate_lsp_actions_all() {
        let config = python_config();
        let grammar = generate_grammar(&config, &[], &LspCapabilities::all());
        assert!(grammar.contains("action complete(position) in @code/python { }"));
        assert!(grammar.contains("action diagnose(range) in @code/python { }"));
        assert!(grammar.contains("action hover(position) in @code/python { }"));
        assert!(grammar.contains("action definition(position) in @code/python { }"));
        assert!(grammar.contains("action references(position) in @code/python { }"));
        assert!(grammar.contains("action tokens(range) in @code/python { }"));
        assert!(!grammar.contains("-- not supported by server"));
    }

    #[test]
    fn generate_lsp_actions_partial() {
        let config = python_config();
        let caps = LspCapabilities {
            completion: true,
            hover: true,
            definition: true,
            references: true,
            diagnostics: true,
            semantic_tokens: false,
        };
        let grammar = generate_grammar(&config, &[], &caps);
        assert!(grammar.contains("action complete(position)"));
        assert!(grammar.contains("-- action tokens(range) in @code/python { }"));
    }

    #[test]
    fn generate_missing_actions_commented() {
        let config = python_config();
        let caps = LspCapabilities::default();
        let grammar = generate_grammar(&config, &[], &caps);
        assert!(grammar.contains("-- not supported by server"));
        assert!(grammar.contains("-- action complete(position) in @code/python { }"));
    }

    #[test]
    fn generate_underscore_stripped_in_fields() {
        let config = python_config();
        let types = vec![NodeType::Product {
            name: "function_definition".into(),
            fields: vec![NodeField {
                name: "return_type".into(),
                multiple: false,
                required: false,
                types: vec!["_type".into()],
            }],
            children: vec![],
        }];
        let grammar = generate_grammar(&config, &types, &LspCapabilities::default());
        assert!(grammar.contains("return_type: option(type)"));
    }

    #[test]
    fn generate_full_python_fixture() {
        let fixture = include_str!("../../fixtures/node-types/python.json");
        let types = super::super::node_types::parse_node_types(fixture).unwrap();
        let config = python_config();
        let grammar = generate_grammar(&config, &types, &LspCapabilities::all());

        assert!(grammar.contains("function_definition"));
        assert!(grammar.contains("class_definition"));
        assert!(grammar.contains("identifier"));
        assert!(grammar.contains("action complete(position)"));
        assert!(grammar.contains("action hover(position)"));
        assert!(grammar.starts_with("-- auto-generated"));
        assert!(grammar.contains("grammar @code/python {"));
        assert!(grammar.ends_with("out @code/python\n"));
    }

    #[test]
    fn format_field_type_single_required() {
        let field = NodeField {
            name: "x".into(),
            multiple: false,
            required: true,
            types: vec!["identifier".into()],
        };
        assert_eq!(format_field_type(&field), "identifier");
    }

    #[test]
    fn format_field_type_single_optional() {
        let field = NodeField {
            name: "x".into(),
            multiple: false,
            required: false,
            types: vec!["identifier".into()],
        };
        assert_eq!(format_field_type(&field), "option(identifier)");
    }

    #[test]
    fn format_field_type_multiple_required() {
        let field = NodeField {
            name: "x".into(),
            multiple: true,
            required: true,
            types: vec!["statement".into()],
        };
        assert_eq!(format_field_type(&field), "[statement]");
    }

    #[test]
    fn format_field_type_multiple_optional() {
        let field = NodeField {
            name: "x".into(),
            multiple: true,
            required: false,
            types: vec!["statement".into()],
        };
        assert_eq!(format_field_type(&field), "option([statement])");
    }

    #[test]
    fn format_field_type_union() {
        let field = NodeField {
            name: "x".into(),
            multiple: false,
            required: true,
            types: vec!["a".into(), "b".into()],
        };
        assert_eq!(format_field_type(&field), "(a | b)");
    }

    #[test]
    fn format_field_type_union_multiple() {
        let field = NodeField {
            name: "x".into(),
            multiple: true,
            required: true,
            types: vec!["a".into(), "b".into()],
        };
        assert_eq!(format_field_type(&field), "[(a | b)]");
    }

    #[test]
    fn strip_underscore_with_prefix() {
        assert_eq!(strip_underscore("_expression"), "expression");
    }

    #[test]
    fn strip_underscore_without_prefix() {
        assert_eq!(strip_underscore("identifier"), "identifier");
    }

    #[test]
    fn generate_no_lsp_command() {
        let config = LanguageConfig {
            name: "test".into(),
            tree_sitter: "tree-sitter-test".into(),
            lsp_command: vec![],
            file_extensions: vec![],
        };
        let grammar = generate_grammar(&config, &[], &LspCapabilities::default());
        assert!(grammar.contains("-- lsp: none"));
    }
}
